# -*- coding: utf-8 -*-
"""AU_Daily_Sales_Cleaned

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtEFQkNFGsEksb5V9SJWDCq1wDzx944H

# Cleaning
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_excel("/content/AU_Daily_Sales.xlsx")
df

df.info()

df.dtypes

df.describe()

df.duplicated().sum()

missing_percentage = df.isnull().mean() * 100
missing_percentage

df.drop(columns=["Wind Gust (mph)","Wind Chill (F)"],inplace=True)

df.columns

df["Temperature (F)"].mean()

df["Temperature (F)"] = df["Temperature (F)"].fillna(df["Temperature (F)"].mean())

df["Temperature Category"] = df["Temperature Category"].fillna("51-60")

df["Humidity (%)"] = df["Humidity (%)"].fillna(df["Humidity (%)"].mean())

df["Wind Speed (mph)"] = df["Wind Speed (mph)"].fillna(df["Wind Speed (mph)"].mean())

df["Wind Direction"] = df["Wind Direction"].fillna("Unknown")

df["Fog (Y/N)"] = df["Fog (Y/N)"].fillna(df["Fog (Y/N)"].mode()[0])

df["Rain (Y/N)"] = df["Rain (Y/N)"].fillna(df["Rain (Y/N)"].mode()[0])

df["Snow (Y/N)"] = df["Snow (Y/N)"].fillna(df["Snow (Y/N)"].mode()[0])

df.isnull().sum()

df.drop_duplicates(inplace=True)

df.dtypes

df["Humidity (%)"] = df["Humidity (%)"].astype(int)

df.dtypes

df.head()

df["Open Date"] = df["Open Date"].dt.strftime("%#m/%#d/%Y %H:%M:%S")

df.dtypes

df["Month Order"] = pd.to_datetime(df["Open Date"]).dt.month

df.head()

"""# Business Question

1. What is the relationship between weather conditions and sales volume?
"""

weather_sales = df.groupby(["Weather Condition"])["Count"].sum().sort_values(ascending=False)
print(weather_sales)

"""2. Which month has the highest number of sales?"""

monthly_sales = df.groupby("Month")["Count"].sum().sort_values(ascending=False)
print(monthly_sales)

"""4. Do rain or snow have an impact on sales volume?"""

rain_sales = df.groupby("Rain (Y/N)")["Count"].sum()
snow_sales = df.groupby("Snow (Y/N)")["Count"].sum()
print("Sales with/without Rain:\n", rain_sales)
print("Sales with/without Snow:\n", snow_sales)

"""5. Which dealer has the highest total sales?"""

top_dealers = df.groupby("Dealer ID")["Count"].sum().sort_values(ascending=False).head(10)
print(top_dealers)

"""5. What is the average number of days it takes to make a sale?"""

avg_days = df["Days to Make Sale"].mean()
print(f"Average Days to Make Sale: {avg_days:.2f}")

"""6. What is the sales distribution across temperature categories?
python
"""

temp_cat_sales = df.groupby("Temperature Category")["Count"].sum()
print(temp_cat_sales)

"""7. Do wind directions influence the number of sales?"""

wind_dir_sales = df.groupby("Wind Direction")["Count"].sum().sort_values(ascending=False)
print(wind_dir_sales)

"""8. How does visibility differ on high-sales vs low-sales days?"""

high_vis = df.sort_values("Count", ascending=False).head(10)["Visibility (mi)"].mean()
low_vis = df.sort_values("Count").head(10)["Visibility (mi)"].mean()

print(f"Average Visibility on Top 10 Sales Days: {high_vis:.2f}")
print(f"Average Visibility on Lowest 10 Sales Days: {low_vis:.2f}")

"""9. How do sales vary across different years?"""

yearly_sales = df.groupby("Year")["Count"].sum()
print(yearly_sales)

"""10. Which days of the month tend to have the highest sales?"""

day_sales = df.groupby("Month Order")["Count"].sum().sort_values(ascending=False)
print(day_sales)

"""11. Do foggy days have lower sales than clear days?"""

fog_sales = df.groupby("Fog (Y/N)")["Count"].sum()
print(fog_sales)

"""12. Is there any seasonality pattern in the sales based on temperature categories?"""

seasonality = df.groupby(["Month", "Temperature Category"])["Count"].sum().unstack().fillna(0)
print(seasonality)

"""# Visuals"""

plt.figure(figsize=(10, 6))
sns.histplot(df["Days to Make Sale"], bins=30, kde=True, color="royalblue")
plt.title("Distribution of Days to Make Sale")
plt.xlabel("Days to Make Sale")
plt.ylabel("Count")
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x="Temperature Category", y="Temperature (F)", data=df, palette="Set2")
plt.title("Temperature Distribution by Category")
plt.xlabel("Weather Category")
plt.ylabel("Temperature (F)")
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 5))
fog_rain_snow = df[["Fog (Y/N)", "Rain (Y/N)", "Snow (Y/N)"]]
for i, col in enumerate(fog_rain_snow.columns):
    plt.subplot(1, 3, i+1)
    sns.countplot(data=df, x=col, palette="viridis")
    plt.title(f"{col} Count")
    plt.xlabel(col)
    plt.ylabel("Count")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
monthly_visibility = df.groupby("Month Order")["Visibility (mi)"].mean().reset_index()
sns.lineplot(data=monthly_visibility, x="Month Order", y="Visibility (mi)", marker="o")
plt.title("Average Visibility by Month")
plt.xlabel("Month")
plt.ylabel("Average Visibility (mi)")
plt.grid(True)
plt.show()

sns.pairplot(df[["Temperature (F)", "Humidity (%)", "Wind Speed (mph)", "Visibility (mi)"]], diag_kind="kde")
plt.suptitle("Pairwise Plot of Weather Variables", y=1.02)
plt.show()

plt.figure(figsize=(8, 5))
sns.barplot(
    data=df,
    x="Temperature Category",
    y="Days to Make Sale",
    palette="coolwarm",
    errorbar=None
)
plt.title("Average Days to Make Sale by Temperature Category")
plt.xlabel("Temperature Category")
plt.ylabel("Average Days to Make Sale")
plt.grid(axis="y")
plt.tight_layout()
plt.show()

df.to_excel("Daily_Saled_data_Cleaned.xlsx", index=False)